name: Branch Protection
on: push

jobs:
  protection-check:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v1
      with:
        node-version: 12.x
    - 
      name: Check
      run: |
        cd ./.github/workflows
        node owner-check.js $GITHUB_ACTOR
