name: Branch Protection
on: push

jobs:
  protection-check:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Set up Node.js
      uses: actions/setup-node@v1
      with:
        node-version: 12.x
    - 
      name: Check Commit
      run: |
        cd ./.github/workflows
        if [ node owner-check.js $GITHUB_ACTOR $GITHUB_REF -eq -1 ]; then echo REJECT; fi
